config/routes.rb
Rails.application.routes.draw do
  

 root to: "welcome#index"

  get "/welcome", to: "welcome#index"

  
  resources :posts
  
  resources :users, except: [:new]
  # get "/users/new", to: "welcome#index", as: "new_user"
  
  resources :places
  
  post "/sessions", to: "sessions#create"

  get "/sessions", to: "sessions#destroy"
  
end

app/models/place.rb
class Place < ActiveRecord::Base
  
  has_many :posts
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :place
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
	validates :password, confirmation: true
	validates :email, uniqueness: true

  has_secure_password

  has_many :posts, dependent: :destroy

  def self.confirm(params)
  	@user = User.find_by({email: params[:email]})
  	@user.try(:authenticate, params[:password])
	end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :logged_in?
	before_action :set_user_place, only: [:edit, :update, :destroy]

	def index
		@places = Place.all	
	end

	def new
		@place = Place.new
	end

	def create
		place = current_user.places.new(place_params)
		if place.save
			redirect_to place_path(place)
		else
			redirect_to new_place_path
		end
	end

	def show		
		@place = Place.find(params[:id])
		@posts = Post.where({place_id: params[:id]}).sort_by(&:updated_at)
	end

	def edit
	end

	def update
		if @place.update_attributes(place_params)
			redirect_to place_path(@place)
		else
			redirect_to edit_place_path(@place)
		end
	end

	def destroy
		@place.destroy()
	end

	private

	def place_params
		white_list = [
						:name, :picture
					]
		params.require(:place).permit(*white_list)
	end

	def set_user_place
		@place = current_user.places.find(params[:id])
		unless @place
			redirect_to places_path
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in?
	before_action :set_user_post, only: [:edit, :update, :destroy]

	def index
		@posts = current_user.posts
	end

	def new
		@post = Post.new
		@places = Place.all
	end

	def create
		post = current_user.posts.new(post_params)
		if post.save
			redirect_to place_path(post.place_id)
		else
			redirect_to new_post_path
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(post_params)
			redirect_to post_path(@post)
		else
			redirect_to edit_post_path(@post)
		end
	end

	def destroy
		@post.destroy()
	end

	private

	def post_params
		white_list = [
				:author, :title, :body, 
				:user_id, :place_id
			     ]
		params.require(:post).permit(*white_list)
	end

	def set_user_post
		@post = current_user.posts.find(params[:id])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
	end

	def create
		user_params = params.require(:user).permit(:email, :password)
		@user = User.confirm(user_params)
		if @user
			login(@user)
			redirect_to "/places"
		else
			redirect_to welcome_path
		end
	end

	def destroy
		logout
		redirect_to ("/")
	end

	private

	def login_params
		user = params.require(:user)
		[user[:email], user[:password]]
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def profile
    redirect_to users_path(current_user)
  end
  
  def create
    user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_city)
    user = User.new(user_params)
    
    if user.save
      login user

      redirect_to "/users/#{user.id}"
    else
      redirect_to "/welcome"
    end
  end

  def index
  	@users = User.all
  end
  
  def show    
  	 @user = User.find(params[:id])      
  end

  def edit
    @user = User.find(params[:id])
  end 

  def update
    # binding.pry
    @user = User.find(params[:id])
  	if @user.update_attributes(user_params)
  		redirect_to user_path(current_user)
  	else
  		redirect_to edit_user_path(current_user)
  	end
  end

  def destroy
  	@user.destroy()
  end

  private

    def set_user
      @user = current_user
    end

    def user_params
      white_list = [
                      :email, :email_confirmation,
                      :password, :password_confirmation,
                      :first_name, :last_name, :current_city
                   ]
      params.require(:user).permit(*white_list)			
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		@current_user || User.find_by({id: session[:user_id]})
	end

	def logged_in?
		unless current_user
			redirect_to ("/welcome")
		end
	end

	def login(user)
		session[:user_id] = user.id
		@current_user = user
	end

	def logout
		@current_user = session[:user_id] = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vagabond</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/places/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Cities Page</title>
	<style>
		h1 {
			color: black;
		}
		p {
			color: black;
		}
	</style>
    <script src="https://cdn.blockspring.com/blockspring.js"></script>
</head>
<body>
	<%= render "/show/navbar"  %>
	
	<h1>Places</h1>
	
	<% @places.each do |place| %>

		<div>
			<a href="/places/<%= place.id %>"><h3><%= place.name %></h3></a>
		</div>

	<% end %>

    <script>
          blockspring.runParsed("interactive-google-map", { "locations": JSON.parse("[[\"latitude\",\"longitude\",\"tooltip\"],[\"37.4217542234\",\"-122.100920271\",\"Somewhere\"],[\"41.895964876906\",\"-87.632716978217\",\"Out\"],[\"28.58230778\",\"77.09399505\",\"There\"]]")}, { "api_key": "" }, function(res){
              var map = (res.params);
              $('body').append(map);
                })
            </script>

</body>
</html>

app/views/places/show.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title></title>
	</head>

	<style type="text/css">
	

		#mainImage {
			height: 400px;
			text-align: center;
		}

		#cityImg {
			max-width: 100%;
			max-height: 100%;
		}

	.navbar-default {
		margin: 0;
	}

	h1 {
		display: block;
	}
	</style>

	<body>
		<%= render "/show/navbar"  %>
		<div id="mainImage">

			<h1><%= @place.name %></h1>
			<img id="cityImg" src="<%= @place.picture %>">
		</div>

		<% @posts.each do |post| %>

			<h3><%= post.title %></h3>
			<h4><%= post.created_at %></h4>
			<p><%= post.body %></p>

		<% end %>

	</body>
</html>

app/views/posts/edit.html.erb
<%= render "/show/navbar"  %>
<%= form_for @post, html: {class: "form-horizontal form-top"}  do |f| %>
			  <div class="form-group">
			    <label for="inputTitle3" class="col-sm-2 control-label">First Name</label>
		    	<div class="col-sm-10">
			    		<%= f.text_field :title, placeholder: "Enter title", class: "form-control" %>
			    </div>
			  </div>
			  <div class="form-group">
			    <label for="inputBody3" class="col-sm-2 control-label">Last Name</label>
			    <div class="col-sm-10">			  
			    	<%= f.text_field :body, placeholder: "Enter description", class: "form-control" %>
			    </div>
			  </div>
			  

			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10">
			  		<%= f.submit "Edit", class: "btn btn-default" %>
			    </div>
			  </div>
				<% end %>    
	    </div>
	  </div>
	</div>

app/views/posts/index.html.erb
<%= render "/show/navbar"  %>
<% @posts.each do |post| %>
  <div class="rendered-data">
    <h3><span class="label label-default">Title:</span><%= post.title %></h3>
    <h3><span class="label label-default">Description:</span><%= post.body %></h3>
  </div>
  <br>
<% end %>
	

app/views/posts/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<style type="text/css">

#post_place_id {
	  margin: 8px 0 8px 16px;
}

</style>
<body>
<%= render "/show/navbar"  %>
    <%= form_for @post, html: {class: "form-horizontal form-top"} do |f| %>
			  <div class="form-group">
			    <label for="inputTitle3" class="col-sm-2 control-label">Title</label>
		    	<div class="col-sm-10">
			    		<%= f.text_field :title, placeholder: "Enter title", class: "form-control" %>
			    </div>
			  </div>
		  
			  <!-- dropdown begin -->
			  
			  <div class="form-group dropdown">
			  	<label for="inputTitle3" class="col-sm-2 control-label">Select a city</label>
			
			  	<div class="controls">
			  		<%= f.select(:place_id, options_for_select([['San Francisco', 1], ['Oakland', 2], ['San Jose', 3]])) %>
			  	</div>
			  </div>	

				<!-- dropdown end -->

			  <div class="form-group">
			    <label for="inputBody3" class="col-sm-2 control-label">Body</label>
			    <div class="col-sm-10">			  
			    	<%= f.text_area :body, placeholder: "Enter description", class: "form-control" %>
			    </div>
			  </div>
			  <div class="form-group">

			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10">
			  		<%= f.submit "Sumbit", class: "btn btn-default" %>
			    </div>
			  </div>
			
		<% end %>   
</body>
</html>

app/views/posts/show.html.erb
<%= render "/show/navbar"  %>

	<div class="rendered-data">

        <h3><span class="label label-default">Title:</span>   <%=@post.title %></h3>
        <h3><span class="label label-default">Description:</span>   <%=@post.body %></h3>
        
    </div>

app/views/show/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
   <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" 
         data-target="#example-navbar-collapse">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Vagabonding</a>
   </div>
   <div class="collapse navbar-collapse" id="example-navbar-collapse">
      <ul class="nav navbar-nav">
         <li><a href="<%= "#{user_path(current_user)}"%>">Profile</a></li>
         <li><a href="<%= "#{edit_user_path(current_user)}"%>">EditProfile</a></li>
         <li><a href="<%= "#{places_path}" %>">Places</a></li>
         <li><a href="<%= "#{new_post_path}" %>">NewPost</a></li>
         <li><a href="<%= "#{sessions_path}" %>">Logout</a></li>
      </ul>
   </div>
</nav>
	</span>

app/views/users/edit.html.erb
<%= render "/show/navbar"  %>
<%= form_for @user, html: {class: "form-horizontal form-top"}  do |f| %>
			  <div class="form-group">
			    <label for="inputFirstName3" class="col-sm-2 control-label">First Name</label>
		    	<div class="col-sm-10">
			    		<%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
			    </div>
			  </div>
			  <div class="form-group">
			    <label for="inputLastName3" class="col-sm-2 control-label">Last Name</label>
			    <div class="col-sm-10">			  
			    	<%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
			    </div>
			  </div>
			  
			  <div class="form-group">
			    <label for="inputCurrentCity3" class="col-sm-2 control-label">Current city</label>
			    <div class="col-sm-10">			  
			    	<%= f.text_field :current_city, placeholder: "Current city", class: "form-control" %>
			    </div>
			  </div>
			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10">
			  		<%= f.submit "Edit", class: "btn btn-default" %>
			    </div>
			  </div>
				<% end %>    
	    </div>
	  </div>
	</div>

app/views/users/index.html.erb
<h1>Welcome to Users Index.</h1>

<div>
  There are currently <%= @users.length %> registered vagabonds.
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <style>
    

    .left-content {
      background-color: #eee;
      height: 600px; 
      border-style: solid;
      border-width: 1px;  

    }

    .right-content {
      height: 600px;
      background-color: #eee;
      border-style: solid;
      border-width: 1px;  
      overflow: scroll;   
    }

    .container h1 {
       color: white;
    }

    header h1 {

      padding-top: 5px;

    }

    .container-fluid h2 {
      padding-left: 140px;

    }

    .rendered-data {
      padding-top: 350px;
      padding-left: 10px;
    } 

    .container {
      padding-bottom: 50px;
    }

  </style>

</head>

<body>

  <% if current_user == @user%>
  <%= render "/show/navbar"  %>

  <div class="container-fluid">
      <h2>Welcome, <small><%= @user.first_name %></small></h2>
  </div>

  <div class="container" ".col-lg">

    <div class="left-content col-md-5">


      <div class="rendered-data">

        <h3><span class="label label-default">First Name:</span>   <%=@user.first_name %></h3>
        <h3><span class="label label-default">Last Name:</span>   <%=@user.last_name %></h3>
        <h3><span class="label label-default">Current City:</span>   <%=@user.current_city %></h3>
        <h3><span class="label label-default">Email:</span>   <%=@user.email %></h3>
        
      </div>

    </div>

    <div class="right-content col-md-6 col-md-offset-1" >

      <div class="page-header">

        <h2><small>Your posts</small></h2>

        <ul>
          <% @user.posts.each do |post| %>
          <li>
          <%= link_to "#{post.title}", post_path(post) %>
          </li>
          <% end %>
        </ul>

      </div>

    </div>

  </div>
  <% else %>
    <script type="text/javascript">
      window.location.href="/welcome"  // put your correct path in a string here
    </script>
  <% end %>

</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Welcome to Vagabonding</title>
</head>
<body>
<div id="wrapper" class="container">
		<div id="box">
			<h1 id="splashHeader">Vagabonding</h1>
			<p id="splashPar">Find travel stories from all over the world</p>	
		</div>

	<div id="buttons">	
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#signup-form">Signup</button>

		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#login-form">Login</button>
	</div>

</div>
	<!-- signup -->
	<div id="signup-form" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	  <div class="modal-dialog modal-lg">
	    <div class="modal-content">
   
	    

   
	      <!-- Signup form start -->

	      <%= form_for @user, html: {class: "form-horizontal form-top"} do |f| %>
			  <div class="form-group">
			    <label for="inputFirstName3" class="col-sm-2 control-label">First Name</label>
		    	<div class="col-sm-10">
			    		<%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
			    </div>
			  </div>
			  <div class="form-group">
			    <label for="inputLastName3" class="col-sm-2 control-label">Last Name</label>
			    <div class="col-sm-10">			  
			    	<%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
			    </div>
			  </div>
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
			    <div class="col-sm-10">			  
			    	<%= f.text_field :email, placeholder: "Email", type: "email", class: "form-control" %>
			    </div>
			  </div>
			  <div class="form-group">
			    <label for="inputCurrentCity3" class="col-sm-2 control-label">Current city</label>
			    <div class="col-sm-10">			  
			    	<%= f.text_field :current_city, placeholder: "Current city", class: "form-control" %>
			    </div>
			  </div>
			  <div class="form-group">
			    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
			    <div class="col-sm-10">
			    	<%= f.password_field :password, placeholder: "Password", class: "form-control" %>
			    </div>
			  </div>
			  <div class="form-group">
			    <label for="inputPassword3" class="col-sm-2 control-label">Confirm Password</label>
			    <div class="col-sm-10">
			    	<%= f.password_field :password_confirmation, placeholder: "Confirm Password", class: "form-control" %>
			    </div>
			  </div>
			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10">
			  		<%= f.submit "Sign Up", class: "btn btn-default" %>
			    </div>
			  </div>
				<% end %>    
	    </div>
	  </div>
	</div>

	<!-- Login -->
	<div id="login-form" class="modal fade bs-example-modal-lg2" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	  <div class="modal-dialog modal-lg">
	    <div class="modal-content">
	      <!-- Login form start -->

	      <%= form_for @user, html: {class: "form-horizontal form-top"}, url: "/sessions", method: "post" do |f| %>
			  
			  <div class="form-group">
			    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
			    <div class="col-sm-10">
			      <%= f.text_field :email, placeholder: "Email", type: "email", class: "form-control" %>
			    </div>
			  </div>

			  <div class="form-group">
			    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
			    <div class="col-sm-10">
			    	<%= f.password_field :password, placeholder: "Password", class: "form-control" %>
			    </div>
			  </div>

			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10">
			      <div class="checkbox">
			        <label>
			          <input type="checkbox"> Remember me
			        </label>
			      </div>
			    </div>
			  </div>

			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10">
			    	<%= f.submit "Sign In", class: "btn btn-default" %>			     
			    </div>
			  </div>	          	       	  
	      <% end %> 


	    </div>
	  </div>
	</div>



<script type="text/javascript">
	$('#wrapper').tubular({videoId: 'ygo5d0UuXB4', start: 26, repeat: true});
</script>
</body>
</html>